image: eclipse-temurin:17-jdk

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./gradlew --no-daemon clean assemble -x test

test:
  stage: test
  script:
    - ./gradlew --no-daemon test

deploy:
  stage: deploy
  when: manual
  allow_failure: false
  script:
    - ./gradlew --no-daemon :notifier-boot2-starter:publishBoot2StarterPublicationToPrivateRepository
    - ./gradlew --no-daemon :notifier-boot3-starter:publishBoot3StarterPublicationToPrivateRepository
  variables:
    MAVEN_REPO_URL: $MAVEN_REPO_URL
    MAVEN_REPO_USERNAME: $MAVEN_REPO_USERNAME
    MAVEN_REPO_PASSWORD: $MAVEN_REPO_PASSWORD
    MAVEN_REPO_ALLOW_INSECURE: $MAVEN_REPO_ALLOW_INSECURE